// <auto-generated />
using System;
using CRM.Models.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRM.Models.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210603171354_updateInvoiceDetail")]
    partial class updateInvoiceDetail
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRM.Models.AccountingPeriod", b =>
                {
                    b.Property<string>("code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 53, 963, DateTimeKind.Local).AddTicks(7375));

                    b.Property<string>("UpdateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 53, 970, DateTimeKind.Local).AddTicks(8792));

                    b.Property<DateTime>("dateLocked")
                        .HasColumnType("datetime2");

                    b.Property<string>("fiscalYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isClosed")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.HasKey("code");

                    b.HasIndex("CreateByusername");

                    b.HasIndex("UpdateByusername");

                    b.ToTable("AccountingPeriod");
                });

            modelBuilder.Entity("CRM.Models.Company", b =>
                {
                    b.Property<string>("code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 53, 983, DateTimeKind.Local).AddTicks(4183));

                    b.Property<string>("UpdateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 53, 983, DateTimeKind.Local).AddTicks(5186));

                    b.Property<string>("address")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("contactPerson")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("contactPosition")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("displayAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("displayFaxNumber")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("displayPhone")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("displayTaxCode")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("displyEmail")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("email")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("faxNumber")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("representPerson")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("representPosition")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("taxCode")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.HasIndex("CreateByusername");

                    b.HasIndex("UpdateByusername");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("CRM.Models.Currency", b =>
                {
                    b.Property<string>("code")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CreateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 53, 988, DateTimeKind.Local).AddTicks(2455));

                    b.Property<string>("UpdateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 53, 988, DateTimeKind.Local).AddTicks(3163));

                    b.Property<bool>("getExchange")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("code");

                    b.HasIndex("CreateByusername");

                    b.HasIndex("UpdateByusername");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("CRM.Models.Customer", b =>
                {
                    b.Property<string>("code")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CreateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 53, 990, DateTimeKind.Local).AddTicks(5411));

                    b.Property<string>("RepresentPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 53, 990, DateTimeKind.Local).AddTicks(6138));

                    b.Property<string>("address")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("bankAccountName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("bankName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("bankNumber")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("contactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerTypecode")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("dateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("identityNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("identityPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("idetityDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("taxCode")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("code");

                    b.HasIndex("CreateByusername");

                    b.HasIndex("UpdateByusername");

                    b.HasIndex("customerTypecode");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("CRM.Models.CustomerType", b =>
                {
                    b.Property<string>("code")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CreateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 52, DateTimeKind.Local).AddTicks(6928));

                    b.Property<string>("UpdateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 52, DateTimeKind.Local).AddTicks(7482));

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.HasIndex("CreateByusername");

                    b.HasIndex("UpdateByusername");

                    b.ToTable("CustomerType");

                    b.HasData(
                        new
                        {
                            code = "1",
                            name = "Doanh nghiệp"
                        },
                        new
                        {
                            code = "0",
                            name = "Cá nhân"
                        });
                });

            modelBuilder.Entity("CRM.Models.GLAccount", b =>
                {
                    b.Property<string>("code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 62, DateTimeKind.Local).AddTicks(7525));

                    b.Property<string>("UpdateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 62, DateTimeKind.Local).AddTicks(8104));

                    b.Property<decimal>("creditAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("debitAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("isCredit")
                        .HasColumnType("bit");

                    b.Property<bool>("isDebit")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("netChange")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("code");

                    b.HasIndex("CreateByusername");

                    b.HasIndex("UpdateByusername");

                    b.ToTable("GLAccount");
                });

            modelBuilder.Entity("CRM.Models.GLCategory", b =>
                {
                    b.Property<string>("code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 55, DateTimeKind.Local).AddTicks(9099));

                    b.Property<string>("UpdateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 55, DateTimeKind.Local).AddTicks(9705));

                    b.Property<string>("name")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("code");

                    b.HasIndex("CreateByusername");

                    b.HasIndex("UpdateByusername");

                    b.ToTable("GLCategory");
                });

            modelBuilder.Entity("CRM.Models.InvoiceDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 66, DateTimeKind.Local).AddTicks(4430));

                    b.Property<string>("UpdateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 66, DateTimeKind.Local).AddTicks(5049));

                    b.Property<string>("functionCode")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("functionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("headercode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("itemCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("itemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("unitCode")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("unitName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("unitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("CreateByusername");

                    b.HasIndex("UpdateByusername");

                    b.HasIndex("functionCode");

                    b.HasIndex("headercode");

                    b.HasIndex("unitCode");

                    b.ToTable("InvoiceDetails");
                });

            modelBuilder.Entity("CRM.Models.InvoiceDetailFunction", b =>
                {
                    b.Property<string>("code")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CreateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 75, DateTimeKind.Local).AddTicks(5879));

                    b.Property<string>("UpdateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 75, DateTimeKind.Local).AddTicks(6763));

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.HasIndex("CreateByusername");

                    b.HasIndex("UpdateByusername");

                    b.ToTable("InvoiceDetailFunction");
                });

            modelBuilder.Entity("CRM.Models.InvoiceHeader", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 79, DateTimeKind.Local).AddTicks(4445));

                    b.Property<string>("UpdateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 79, DateTimeKind.Local).AddTicks(4980));

                    b.Property<DateTime?>("accountingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("accountingPersonusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("creditAccountcode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currencyInText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerBankAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerBankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customerTaxCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("debitAccountcode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("documentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("eInvoicePublish")
                        .HasColumnType("bit");

                    b.Property<decimal>("exChangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("invoiceNo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("invoiceStatuscode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("invoiceTypecode")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("patern")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("paymentMethodcode")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("paymentTermcode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("publishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("sellerAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sellerBankAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sellerBankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sellerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sellerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sellerTaxCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("serial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("totalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("totalNoTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("totalTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("totalWithTax")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("code");

                    b.HasIndex("CreateByusername");

                    b.HasIndex("UpdateByusername");

                    b.HasIndex("accountingPersonusername");

                    b.HasIndex("creditAccountcode");

                    b.HasIndex("debitAccountcode");

                    b.HasIndex("invoiceStatuscode");

                    b.HasIndex("invoiceTypecode");

                    b.HasIndex("paymentMethodcode");

                    b.HasIndex("paymentTermcode");

                    b.ToTable("InvoiceHeaders");
                });

            modelBuilder.Entity("CRM.Models.InvoiceStatus", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 82, DateTimeKind.Local).AddTicks(1252));

                    b.Property<string>("UpdateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 82, DateTimeKind.Local).AddTicks(2436));

                    b.Property<bool>("allowEdit")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("code");

                    b.HasIndex("CreateByusername");

                    b.HasIndex("UpdateByusername");

                    b.ToTable("InvoiceStatus");
                });

            modelBuilder.Entity("CRM.Models.InvoiceType", b =>
                {
                    b.Property<string>("code")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CreateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 85, DateTimeKind.Local).AddTicks(2485));

                    b.Property<string>("UpdateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 85, DateTimeKind.Local).AddTicks(3005));

                    b.Property<string>("name")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.HasIndex("CreateByusername");

                    b.HasIndex("UpdateByusername");

                    b.ToTable("InvoiceType");
                });

            modelBuilder.Entity("CRM.Models.PaymentMethod", b =>
                {
                    b.Property<string>("code")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CreateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 87, DateTimeKind.Local).AddTicks(9171));

                    b.Property<string>("UpdateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 87, DateTimeKind.Local).AddTicks(9886));

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.HasIndex("CreateByusername");

                    b.HasIndex("UpdateByusername");

                    b.ToTable("PaymentMethod");
                });

            modelBuilder.Entity("CRM.Models.PaymentStatus", b =>
                {
                    b.Property<string>("code")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CreateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 91, DateTimeKind.Local).AddTicks(1347));

                    b.Property<string>("UpdateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 91, DateTimeKind.Local).AddTicks(1958));

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.HasIndex("CreateByusername");

                    b.HasIndex("UpdateByusername");

                    b.ToTable("PaymentStatus");
                });

            modelBuilder.Entity("CRM.Models.PaymentTerm", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 93, DateTimeKind.Local).AddTicks(8501));

                    b.Property<string>("UpdateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 93, DateTimeKind.Local).AddTicks(9146));

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("code");

                    b.HasIndex("CreateByusername");

                    b.HasIndex("UpdateByusername");

                    b.ToTable("PaymentTerm");
                });

            modelBuilder.Entity("CRM.Models.SequenceNumber", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 95, DateTimeKind.Local).AddTicks(9485));

                    b.Property<string>("UpdateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 96, DateTimeKind.Local).AddTicks(127));

                    b.Property<string>("lastNumber")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasDefaultValue("000000000");

                    b.Property<string>("numberFrom")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasDefaultValue("000000000");

                    b.Property<string>("numberTo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasDefaultValue("999999999");

                    b.Property<string>("partern")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasDefaultValue("");

                    b.Property<string>("prefix")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasDefaultValue("");

                    b.Property<string>("serial")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasDefaultValue("");

                    b.Property<string>("subfix")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasDefaultValue("");

                    b.HasKey("id");

                    b.HasIndex("CreateByusername");

                    b.HasIndex("UpdateByusername");

                    b.ToTable("SequenceNumber");
                });

            modelBuilder.Entity("CRM.Models.TaxType", b =>
                {
                    b.Property<string>("code")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CreateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 99, DateTimeKind.Local).AddTicks(9606));

                    b.Property<string>("UpdateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 100, DateTimeKind.Local).AddTicks(91));

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("percent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("code");

                    b.HasIndex("CreateByusername");

                    b.HasIndex("UpdateByusername");

                    b.ToTable("TaxType");
                });

            modelBuilder.Entity("CRM.Models.Unit", b =>
                {
                    b.Property<string>("code")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CreateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 102, DateTimeKind.Local).AddTicks(3838));

                    b.Property<string>("UpdateByusername")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 6, 4, 0, 13, 54, 102, DateTimeKind.Local).AddTicks(4470));

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("code");

                    b.HasIndex("CreateByusername");

                    b.HasIndex("UpdateByusername");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("CRM.Models.User", b =>
                {
                    b.Property<string>("username")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<string>("avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hashKey")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("username");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CRM.Models.AccountingPeriod", b =>
                {
                    b.HasOne("CRM.Models.User", "CreateBy")
                        .WithMany()
                        .HasForeignKey("CreateByusername");

                    b.HasOne("CRM.Models.User", "UpdateBy")
                        .WithMany()
                        .HasForeignKey("UpdateByusername");

                    b.Navigation("CreateBy");

                    b.Navigation("UpdateBy");
                });

            modelBuilder.Entity("CRM.Models.Company", b =>
                {
                    b.HasOne("CRM.Models.User", "CreateBy")
                        .WithMany()
                        .HasForeignKey("CreateByusername");

                    b.HasOne("CRM.Models.User", "UpdateBy")
                        .WithMany()
                        .HasForeignKey("UpdateByusername");

                    b.Navigation("CreateBy");

                    b.Navigation("UpdateBy");
                });

            modelBuilder.Entity("CRM.Models.Currency", b =>
                {
                    b.HasOne("CRM.Models.User", "CreateBy")
                        .WithMany()
                        .HasForeignKey("CreateByusername");

                    b.HasOne("CRM.Models.User", "UpdateBy")
                        .WithMany()
                        .HasForeignKey("UpdateByusername");

                    b.Navigation("CreateBy");

                    b.Navigation("UpdateBy");
                });

            modelBuilder.Entity("CRM.Models.Customer", b =>
                {
                    b.HasOne("CRM.Models.User", "CreateBy")
                        .WithMany()
                        .HasForeignKey("CreateByusername");

                    b.HasOne("CRM.Models.User", "UpdateBy")
                        .WithMany()
                        .HasForeignKey("UpdateByusername");

                    b.HasOne("CRM.Models.CustomerType", "customerType")
                        .WithMany()
                        .HasForeignKey("customerTypecode");

                    b.Navigation("CreateBy");

                    b.Navigation("customerType");

                    b.Navigation("UpdateBy");
                });

            modelBuilder.Entity("CRM.Models.CustomerType", b =>
                {
                    b.HasOne("CRM.Models.User", "CreateBy")
                        .WithMany()
                        .HasForeignKey("CreateByusername");

                    b.HasOne("CRM.Models.User", "UpdateBy")
                        .WithMany()
                        .HasForeignKey("UpdateByusername");

                    b.Navigation("CreateBy");

                    b.Navigation("UpdateBy");
                });

            modelBuilder.Entity("CRM.Models.GLAccount", b =>
                {
                    b.HasOne("CRM.Models.User", "CreateBy")
                        .WithMany()
                        .HasForeignKey("CreateByusername");

                    b.HasOne("CRM.Models.User", "UpdateBy")
                        .WithMany()
                        .HasForeignKey("UpdateByusername");

                    b.Navigation("CreateBy");

                    b.Navigation("UpdateBy");
                });

            modelBuilder.Entity("CRM.Models.GLCategory", b =>
                {
                    b.HasOne("CRM.Models.User", "CreateBy")
                        .WithMany()
                        .HasForeignKey("CreateByusername");

                    b.HasOne("CRM.Models.User", "UpdateBy")
                        .WithMany()
                        .HasForeignKey("UpdateByusername");

                    b.Navigation("CreateBy");

                    b.Navigation("UpdateBy");
                });

            modelBuilder.Entity("CRM.Models.InvoiceDetail", b =>
                {
                    b.HasOne("CRM.Models.User", "CreateBy")
                        .WithMany()
                        .HasForeignKey("CreateByusername");

                    b.HasOne("CRM.Models.User", "UpdateBy")
                        .WithMany()
                        .HasForeignKey("UpdateByusername");

                    b.HasOne("CRM.Models.InvoiceDetailFunction", "function")
                        .WithMany()
                        .HasForeignKey("functionCode");

                    b.HasOne("CRM.Models.InvoiceHeader", "header")
                        .WithMany("details")
                        .HasForeignKey("headercode");

                    b.HasOne("CRM.Models.Unit", "unit")
                        .WithMany()
                        .HasForeignKey("unitCode");

                    b.Navigation("CreateBy");

                    b.Navigation("function");

                    b.Navigation("header");

                    b.Navigation("unit");

                    b.Navigation("UpdateBy");
                });

            modelBuilder.Entity("CRM.Models.InvoiceDetailFunction", b =>
                {
                    b.HasOne("CRM.Models.User", "CreateBy")
                        .WithMany()
                        .HasForeignKey("CreateByusername");

                    b.HasOne("CRM.Models.User", "UpdateBy")
                        .WithMany()
                        .HasForeignKey("UpdateByusername");

                    b.Navigation("CreateBy");

                    b.Navigation("UpdateBy");
                });

            modelBuilder.Entity("CRM.Models.InvoiceHeader", b =>
                {
                    b.HasOne("CRM.Models.User", "CreateBy")
                        .WithMany()
                        .HasForeignKey("CreateByusername");

                    b.HasOne("CRM.Models.User", "UpdateBy")
                        .WithMany()
                        .HasForeignKey("UpdateByusername");

                    b.HasOne("CRM.Models.User", "accountingPerson")
                        .WithMany()
                        .HasForeignKey("accountingPersonusername");

                    b.HasOne("CRM.Models.GLAccount", "creditAccount")
                        .WithMany()
                        .HasForeignKey("creditAccountcode");

                    b.HasOne("CRM.Models.GLAccount", "debitAccount")
                        .WithMany()
                        .HasForeignKey("debitAccountcode");

                    b.HasOne("CRM.Models.InvoiceStatus", "invoiceStatus")
                        .WithMany()
                        .HasForeignKey("invoiceStatuscode");

                    b.HasOne("CRM.Models.InvoiceType", "invoiceType")
                        .WithMany()
                        .HasForeignKey("invoiceTypecode");

                    b.HasOne("CRM.Models.PaymentMethod", "paymentMethod")
                        .WithMany()
                        .HasForeignKey("paymentMethodcode");

                    b.HasOne("CRM.Models.PaymentTerm", "paymentTerm")
                        .WithMany()
                        .HasForeignKey("paymentTermcode");

                    b.Navigation("accountingPerson");

                    b.Navigation("CreateBy");

                    b.Navigation("creditAccount");

                    b.Navigation("debitAccount");

                    b.Navigation("invoiceStatus");

                    b.Navigation("invoiceType");

                    b.Navigation("paymentMethod");

                    b.Navigation("paymentTerm");

                    b.Navigation("UpdateBy");
                });

            modelBuilder.Entity("CRM.Models.InvoiceStatus", b =>
                {
                    b.HasOne("CRM.Models.User", "CreateBy")
                        .WithMany()
                        .HasForeignKey("CreateByusername");

                    b.HasOne("CRM.Models.User", "UpdateBy")
                        .WithMany()
                        .HasForeignKey("UpdateByusername");

                    b.Navigation("CreateBy");

                    b.Navigation("UpdateBy");
                });

            modelBuilder.Entity("CRM.Models.InvoiceType", b =>
                {
                    b.HasOne("CRM.Models.User", "CreateBy")
                        .WithMany()
                        .HasForeignKey("CreateByusername");

                    b.HasOne("CRM.Models.User", "UpdateBy")
                        .WithMany()
                        .HasForeignKey("UpdateByusername");

                    b.Navigation("CreateBy");

                    b.Navigation("UpdateBy");
                });

            modelBuilder.Entity("CRM.Models.PaymentMethod", b =>
                {
                    b.HasOne("CRM.Models.User", "CreateBy")
                        .WithMany()
                        .HasForeignKey("CreateByusername");

                    b.HasOne("CRM.Models.User", "UpdateBy")
                        .WithMany()
                        .HasForeignKey("UpdateByusername");

                    b.Navigation("CreateBy");

                    b.Navigation("UpdateBy");
                });

            modelBuilder.Entity("CRM.Models.PaymentStatus", b =>
                {
                    b.HasOne("CRM.Models.User", "CreateBy")
                        .WithMany()
                        .HasForeignKey("CreateByusername");

                    b.HasOne("CRM.Models.User", "UpdateBy")
                        .WithMany()
                        .HasForeignKey("UpdateByusername");

                    b.Navigation("CreateBy");

                    b.Navigation("UpdateBy");
                });

            modelBuilder.Entity("CRM.Models.PaymentTerm", b =>
                {
                    b.HasOne("CRM.Models.User", "CreateBy")
                        .WithMany()
                        .HasForeignKey("CreateByusername");

                    b.HasOne("CRM.Models.User", "UpdateBy")
                        .WithMany()
                        .HasForeignKey("UpdateByusername");

                    b.Navigation("CreateBy");

                    b.Navigation("UpdateBy");
                });

            modelBuilder.Entity("CRM.Models.SequenceNumber", b =>
                {
                    b.HasOne("CRM.Models.User", "CreateBy")
                        .WithMany()
                        .HasForeignKey("CreateByusername");

                    b.HasOne("CRM.Models.User", "UpdateBy")
                        .WithMany()
                        .HasForeignKey("UpdateByusername");

                    b.Navigation("CreateBy");

                    b.Navigation("UpdateBy");
                });

            modelBuilder.Entity("CRM.Models.TaxType", b =>
                {
                    b.HasOne("CRM.Models.User", "CreateBy")
                        .WithMany()
                        .HasForeignKey("CreateByusername");

                    b.HasOne("CRM.Models.User", "UpdateBy")
                        .WithMany()
                        .HasForeignKey("UpdateByusername");

                    b.Navigation("CreateBy");

                    b.Navigation("UpdateBy");
                });

            modelBuilder.Entity("CRM.Models.Unit", b =>
                {
                    b.HasOne("CRM.Models.User", "CreateBy")
                        .WithMany()
                        .HasForeignKey("CreateByusername");

                    b.HasOne("CRM.Models.User", "UpdateBy")
                        .WithMany()
                        .HasForeignKey("UpdateByusername");

                    b.Navigation("CreateBy");

                    b.Navigation("UpdateBy");
                });

            modelBuilder.Entity("CRM.Models.InvoiceHeader", b =>
                {
                    b.Navigation("details");
                });
#pragma warning restore 612, 618
        }
    }
}
